name: Run Folder1 Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Platform-App/Folder1/Code

    steps:
      - name: Checkout Platform-App
        uses: actions/checkout@v3
        with:
          path: platform-app

      - name: Run main1.py
        run: python3 main1.py
