name: Run Folder1 Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Platform-App
        uses: actions/checkout@v3
        with:
          path: platform-app

      - name: List contents for debugging
        run: |
          echo "Listing files in the Platform-App directory"
          ls -R platform-app
        working-directory: .

      - name: Run main1.py
        run: python3 platform-app/Folder1/Code/main1.py
