name: Run Folder1 Main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Platform-App
        uses: actions/checkout@v3
        with:
          path: platform-app

      - name: List contents for debugging
        run: ls -R platform-app/Folder1
        working-directory: platform-app

      - name: Run main1.py
        run: python3 Code/main1.py
        working-directory: platform-app/Folder1
